### ISSUE TITLE
Adding "Open 24hrs" option to Service Hours content type

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#20]
**Is your feature request related to new functionality not yet included in the product? Please describe.**
New functionality. In service hours content types, I would like the start or end time choice of 00:00:00 (or no choice made) to display as "Open 24hrs." 

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
At the Woodruff Library Building, Sundays open at 11am and then remain open for 24 hours. 

Several locations in the building close after midnight, while there is no obvious option to display that the building remains open through the night. 

Starting on Monday, the building is open 24 hours. The building remains open 24 hours through Thursday and into Friday, which then closes at midnight.

**Describe the solution you'd like**
an "Open 24 hours" choice for either the start or end time, or a default choice (00:00:00) that displays Open 24 hours on site.

**Describe alternatives you've considered**
Choosing 6am as a closing time for the building (a time later than the early morning closings within the building).
Choosing 12am as a start time for Fridays.
Visually, this causes some confusion.

**How will this impact users?**
It will clearly display the building hours for users, without second guessing if the building is open in relation to the services points within. 

**Additional context**

Example of WLB Sundays closing at midnight while service points close later:

![WLB Sundays](https://user-images.githubusercontent.com/58950697/189687641-732f33e1-7a93-4473-9af0-f2b0389b26f4.png)

Example of WLB Thursdays to Fridays (Thursday are open 24 hours while Fridays need a start time):

![WLB Thursday to Friday](https://user-images.githubusercontent.com/58950697/189687789-3f3db659-c024-4a4e-9e1a-ac8018bda10c.png)

Conversation/issue/solution on Drupal:

https://www.drupal.org/project/office_hours/issues/3065358

**Comment by maxdmayhew** [comment]
![Screenshot 2023-06-12 at 1.21.58 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/1e43486d-0379-497c-8381-b0b151bbb1fe)

this issue has been resolved since I started working here. oct 3, 2022.

**Comment by maxdmayhew** [comment]
![Screenshot 2023-07-03 at 11.51.03 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/68ddea24-f166-4226-b914-47d1778bf9e2)

![Screenshot 2023-07-03 at 11.51.46 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/e140cfb6-3610-49fe-a5f9-80a389b1501e)

![Screenshot 2023-07-03 at 11.51.28 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/0a55fd80-45fc-408d-bbf9-f2272052cc71)

The above are 3 different ideas that we could implement for the hours page. I do not think there is really an obvious solution. I suggest we ask internally to our teams what makes the most sense, preferably without context.

I personally think that since a day ends at 12AM displaying "11:00AM - Open 24 Hours" does not logically make sense to me. I also believe showing "11:00AM - " without an end date is also confusing. To me the best solution is the default which we have currently.

@rotated8 @lovinscari @cwbragg thoughts?

**Comment by maxdmayhew** [comment]
https://web-prod.lib.utexas.edu/about/hours

Here is another idea for handling hours.

![Screenshot 2023-07-03 at 1.57.04 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/7dac2bc3-a449-4021-8aca-4e3636e6c022)

**Comment by cwbragg** [comment]
I like this utexas one. So per the Woodruff Library Building example, "Opens at 11am" would be displayed on Sundays?

**Comment by cwbragg** [comment]
Excellent!

**Comment by cwbragg** [comment]
I am closing this ticket - the libraries have made the decision to move away from being open 24 hours.
