### ISSUE TITLE
Drupal Forms and Spam

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/web-enhance#24]
Need to enhance our drupal forms to address spam. Currently we have the re-route module implemented.

This enhancement will look at updating what we use for spam filtering. The work involved is intended to include looking at re-route and honeypot for a possible solution to improve spam filtering.

https://wiki.emory.edu/pages/viewpage.action?spaceKey=ELWP&title=reCAPTCHA+Module+and+associated+Captcha+Services

**Comment by CB987** [comment]
looking at [antibot](https://www.drupal.org/project/antibot)-- some commenters on drupal support slack recommend it.

**Comment by CB987** [comment]
next step: try using recaptcha, honeypot, and antibot together and see how that works .

**Comment by CB987** [comment]
with PR #729, antibot and honeypot are now merged to main and deployed to dev. we still have reroute email enabled as well, and have to test on prod before we can disable it.

**Comment by lovinscari** [comment]
@CB987 - I am returning from vacation and wondering if there is something we need to test with this?

**Comment by CB987** [comment]
@lovinscari -- there's limited testing we can do until it gets to prod, where the actual "live" spam is coming in. @maxdmayhew and I have tested locally to ensure that submitting to the forms still works as expected. We will leave the reroute email settings (what is blocking the non-emory emails from coming in) in place until we see how the spam filters are working (because we can see on the backend how much is still coming through, to compare), so that the departments are not flooded with spam until we have assessed how the new modules are working. Let me know if that does not sound acceptable or make sense!
