### ISSUE TITLE
Hyperlinking Subject Area Directory links for Oxford Library 

### ISSUE THREAD

**Issue by bbrown8** [emory-libraries/web-enhance#33]
When patrons click on subject area hyperlink tags under the Oxford Library's directory (https://oxford.library.emory.edu/about/staff-directory), those subject area links do not go anywhere. Could these subject area links point to our Research Engagement Program page? https://oxford.library.emory.edu/faculty-support/research-engagement-program

**Comment by maxdmayhew** [comment]
start by removing the links. Moving to backlog.

@cwbragg @lovinscari we can review this at a later date.

**Comment by CB987** [comment]
so Subject Area is a taxonomy
in default, when you click on a subject, it redirects to 
contact/subject-librarian-directory?field_subject_areas_target_id_1[]=56
that link is set in the /admin/cohestion/templates/content_templates/taxonomy_term/taxonomy_term_subject_areas_subj/edit?destination=/admin/cohesion/templates/content_templates/taxonomy_term in the layout link. 
we can change that from an internal link to a URL, which would link it to the libraries page, but i don't know if we can carry the term ID token into an external URL? tthen it would go to all emory librarians, not just oxford ones. 
because it's a taxonomy term, if we just remove that as a link then it removes it for everybody, not just oxford. (unless we config split it? can config split taxonomy terms?) OR we can give oxford a subject librarian view with the same path, but they only have a few librarians. 
could we add a redirect? are redirects site-specific (an oxford redirect would just be for oxford)-- looks like it. So I can implement the requested fix by putting in a redirect just for oxford. it looks like redirects also count as content, not anything that can be exported, so i will try making the change directly in prod. 
change is made. i'll contact Ben to see if it works the way he is expecting.

**Comment by CB987** [comment]
change is made. i've emailed Ben to see if it works the way he is expecting.

**Comment by CB987** [comment]
i heard back from Ben via email that this solutions works well for them. Change is already on prod so I'm moving this to done.

**Comment by bbrown8** [comment]
[celebrate]     Brown, Ben reacted to your message:
________________________________
From: C Barton ***@***.***>
Sent: Friday, November 17, 2023 5:31:49 PM
To: emory-libraries/web-enhance ***@***.***>
Cc: Brown, Ben ***@***.***>; Author ***@***.***>
Subject: [External] Re: [emory-libraries/web-enhance] Hyperlinking Subject Area Directory links for Oxford Library (Issue #33)


i heard back from Ben via email that this solutions works well for them. Change is already on prod so I'm moving this to done.
